### ISSUE TITLE
Change maintainer

### ISSUE THREAD

**Issue by buep** [code-cafes/git-phlow#303]

**Comment by groenborg** [comment]
Is the project not community driven?

**Comment by groenborg** [comment]
Hi @lakruzz @buep 

I have been removed as a maintainer from the project, but I was still managing the issues and trying to sustain the project. However that seems a tad bit more difficult now.

**Comment by buep** [comment]
I just removed you from our github org... it seems you're still an external collaborator for historical reason on this repo, so you still have write permissions.

This issues about maintainer was just to update the readme to make sure you're not mentioned as maintainer, since we wouldn't expect you to work on the project in your spare time.

But as I said you still have write permissions and we can just coordinate the work :-)

**Comment by buep** [comment]
I'll leave you in the readme as maintainer for now, but Michael isn't spending time on it so it should be updated anyway.

**Comment by groenborg** [comment]
I believe the maintainer is the figure who is maintaining the community and managing the issues, and not meant as the developer, though actual development work is not excluded. Since noone but me is looking at this repo on a daily basis I believe that maintainer is still a fitting title. However the work I do is minimal, but I am however wrapping up the work on the Gitlab integration.. It does take time because I am juggling my own project and a full time job on the sideline :)
