### ISSUE TITLE
[GitHub API] Deprecation notice for authentication via URL query parameters

### ISSUE THREAD

**Issue by DavidCarl** [code-cafes/git-phlow#315]
```
Hi,

On February 7th, 2020 at 10:11 (UTC) your personal access token (git phlow) using Go-http-client/1.1 was used as part of a query parameter to access an endpoint through the GitHub API:

https://api.github.com/repositories/207762919

Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated.

Depending on your API usage, we'll be sending you this email reminder once every 3 days for each token and User-Agent used in API calls made on your behalf.
Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.

Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.

Thanks,
The GitHub Team
```

It seems like GitHub has made some changes that require some rework on git phlows part. This is the attached email we are getting from GitHub.

**Comment by groenborg** [comment]
Yes, there is a deprecation notice in their v3 API. You can find it here: https://developer.github.com/v3/#authentication 

The issue is around here somewhere. 
https://github.com/Praqma/git-phlow/blob/fec9d58804e175062d4bf12bfa496e00ffe425d1/plugins/github.go#L25-L29

To solve this it looks like we need a new authorization strategy because most of their authorization APIs are being discontinued, the preferred way seems to be a web flow: https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#web-application-flow

**Comment by DavidCarl** [comment]
Okay its good to hear that it is known. 

I might take a look into this issue and see if I can manage to resolve it, my skills in GoLang is fairly new.

**Comment by groenborg** [comment]
I am going to submit my PR this week.
